pvlib/pvanalytics

.readthedocs.yml

read-the-docs needs the package to be installed so that autodoc can
find the modules it is documenting

Install package locally for read-the-docs build

---

.travis.yml

Github actions do not expose secrets for PRs from forks. This means that in order to upload coverage reports for PRs from a github action we would have to expose the REPO_TOKEN. As a work around we  can build on travis for PRs and upload to coveralls from there.

Use travis for uploading coverage reports to coveralls

---

MANIFEST.in
setup.py

Closes #12 
@wholmgren pointed out that versioneer is no longer maintained. setuptools_scm achieves the same automatic version number management and is very easy to use. It also does not require committing extra files to the repo. Seems like a win-win to me.

use setuptools_scm to manage version numbers

---

.travis.yml
pvanalytics/tests/test_pvanalytics.py

Previously only built coverage reports for pull requests, but we might
as well build and upload them for all events.

Build and upload coverage reports for all triggers

---

pvanalytics/quality/irradiance.py
pvanalytics/quality/util.py
pvanalytics/tests/quality/test_irradiance.py
pvanalytics/tests/quality/test_util.py

This is a useful function for many QA tasks. Having it in a publicly accessible module will not only allow users to write their own limit-based quality tests, but will let us use it in quality tests in other modules.

Make check_limits quality function public

---

docs/api.rst
docs/licenses.rst
pvanalytics/features.py
pvanalytics/tests/test_features.py

Detects inverter clipping based on levels in the data.
* `detect_clipping` renamed to `features.clipping_levels`
* remove `@mask_flags` decorator
* rewrote tests to avoid depending on pvlib to generate data.

Port detect_clipping from Solar Forecast Arbiter

---

docs/api.rst
docs/licenses.rst
pvanalytics/quality/weather.py
pvanalytics/tests/quality/test_weather.py

Extreme value filters for air temperature, relative humidity, and wind speed ported from SolarForecastArbiter (SFA). These functions just wrap `quality.util.check_limits()` providing reasonable defaults for each type of data.
* remove `@mask_flags` decorator
* the name of the returned Boolean series is not set.
* rename `validator.check_temperature_limits()` to `weather.temperature_limits()`
* rename `validator.check_rh_limits()` to `weather.relative_humidity_limits()`
* rename `validator.check_wind_limits()` to `weather.wind_limits()`

Port weather data validation checks from SolarForecastArbiter

---

docs/api.rst
docs/licenses.rst
pvanalytics/quality/irradiance.py
pvanalytics/tests/quality/test_irradiance.py

Adds quality test to flag irradiance measurements that exceed the expected clearsky irradiance.
* consolidate POA and GHI checks into a single function. These were separate in SFA, but ultimately do exactly the same thing. For pvanalytics it makes sense to consolidate them into a single general purpose function: `quality.irradiance.clearsky_limits()`.
* remove the `@mask_flags` decorator.

Port clearsky-based quality checks from Solar Forecast Arbiter

---

docs/api.rst
docs/licenses.rst
pvanalytics/features/clearsky.py
pvanalytics/tests/features/conftest.py
pvanalytics/tests/features/test_clearsky.py
pvanalytics/tests/features/test_clipping.py

* renamed `validator.detect_clearsky` to `features.clearsky.reno`
* wrote new tests that do not depend on pvlib to generate cleasky data.

Port detect_clearsky from Solar Forecast Arbiter

---

LICENSES/PVFLEETS_QA_LICENSE
docs/api.rst
pvanalytics/quality/gaps.py
pvanalytics/tests/quality/test_gaps.py

Many data-sets come with leading and trailing periods that have sporadic or completely missing data. This adds two functions for identifying and removing these periods:
* `quality.gaps.valid_between()` gives the first and last valid dates in the series.
* `quality.gaps.trim()` returns a boolean mask that is True for the valid period between the dates given by `valid_between`.
These functions both operate on days in the data set, marking all data for each day as valid/invalid based on the number of hours of data that exists on each day. Any data point with a value other than `NaN` is considered "valid" data.

Trim leading and trailing periods of missing data

---

LICENSES/PVFLEETS_QA_LICENSE
docs/api.rst
pvanalytics/quality/util.py
pvanalytics/tests/quality/test_util.py

This catches shifts in data that are apparent when the minimum value for a day is too large.
For days where the minimum value is too high all data data on that day is marked `True`. The original pvfleets function returned the opposite (that behavior can be achieved with the 'bitwise' negation of `~daily_min(...)`)

Implement daily minimum quality filtering

---

pvanalytics/quality/gaps.py
pvanalytics/tests/quality/test_gaps.py

Closes #43 
Adds kwarg `label_all` to `gaps.stale_values_diff` and `gaps.interpolation_diff`. If `label_all=True` then every point in a window that appears interpolated or stale is marked `True`. If `label_all=False` then only the endpoint of the window is marked `True`.

Optionally label every interpolated/stale point (not just endpoints)

---

pvanalytics/__init__.py
pvanalytics/features/__init__.py
pvanalytics/fitting/__init__.py
pvanalytics/quality/__init__.py

Adds import statements to `__init__.py`s so sub-modules are visible after importing their parent module. For example:
```python
from pvanalytics import quality
quality.gaps.trim_incomplete(...)
```

Set up correct import structure

---

pvanalytics/quality/gaps.py
pvanalytics/tests/quality/test_gaps.py

Adds `'end'`, `'all'`, and `'tail'` to the options for labelling points in a
stale/interpolated window. Changes the default behavior to `label='tail'`
which labels every point in the window except the first.
Closes #43

Expanded labeling options for functions in gaps

---

docs/api.rst
pvanalytics/quality/gaps.py
pvanalytics/tests/quality/test_gaps.py

Implementation of the stale value detection method from the pvfleets_qa_analysis code.
This is a very similar function to `stale_values_diff`, but it is based on the difference between consecutive data points after rounding rather than putting a lower bound on the differences. It is also more aggressive in what it considers stale, marking the full sequence of repeated values, rather than just a suffix of the sequence as in `stale_values_diff`.

rounding-based stale value detection

---

LICENSES/PVFLEETS_QA_LICENSE
docs/api.rst
pvanalytics/features/clipping.py
pvanalytics/tests/features/test_clipping.py

Detect clipping in power data by identifying a clipping threshold (through the derivative of the 99.5% quantile of the daily power curve).
All data greater than or equal to the clipping threshold is marked as "clipped".

Port derivative-/quantile-based clipping detection from pvfleets QA

---

.travis.yml

Travis is having problems because the default version of pytest for
python < 3.8 is too old for the newest version of pytest-cov (2.10.0).

bump pytest version for Travis builds

---

setup.py

Use `setuptools.find_packages()` to find all the subpackages. Excludes `tests` package and subpackages.
Closes #58

Include all sub-packages in distribution

---

docs/api.rst
pvanalytics/quality/irradiance.py
pvanalytics/tests/quality/test_irradiance.py

Identify days where the total irradiance is too high or too low. This catches incorrectly labeled sensors (e.g. labeled GHI, but actually POA) or days with strange shifts (for example I saw a data set where the units change from Watts to Milliwatts for a week or two). Existing functions might also catch these, but the aggregate daily check seems like a worthwhile addition to me.

Daily insolation limits

---

pvanalytics/features/orientation.py
pvanalytics/tests/util/test_fit.py
pvanalytics/util/_fit.py

Since these functions are used in a `pandas.GroupBy.apply()` call, manipulating the index to calculate minute of the day can significantly reduce performance. Here we remove the `_get_minute_of_day()` function and instead pass in the x values as a parameter. In addition to improving performance this makes the curve fitting code cleaner and substantially more general.

Refactor curve fitting functions

---

docs/api.rst
pvanalytics/features/orientation.py
pvanalytics/system.py
pvanalytics/tests/conftest.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/test_system.py
pvanalytics/util/_fit.py

From scratch re-implementation of the algorithm form PVFleets QA. There are two substantial differences:
* Caller must pass a list of candidate azimuths and tilts. The PVFleets version includes an extra step where the candidate azimuths are chosen based on the data and uses a fixed set of tilts.
* The index of the solar position Series must cover the same time period as the data. In the PVFleets implementation only one year of solar position data is used. This adds some complexity that I think can be avoided by just requiring users pass in solar position for the same time period as the data. Users can pass arbitrary frequency solar position data and solar azimuth will be resampled and interpolated at 1-minute intervals before it is used. For the best results users should pass 1-minute …

Infer azimuth and tilt from power or POA irradiance

---

.coveragerc
.github/workflows/lint-and-test.yml
.travis.yml
docs/api.rst
pvanalytics/features/daytime.py
pvanalytics/tests/conftest.py
pvanalytics/tests/features/test_daytime.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/quality/test_irradiance.py
pvanalytics/tests/quality/test_weather.py
requirements.txt

Flag daytime periods based on power or irradiance data. Requires no knowledge of location or timezone. Reimplimentation of algorithm from PVFleets with some modifications. In a nutshell it looks for times where the derivative (approximated as a first-order difference) is non-zero and the data is large. Can handle intermittent periods of low values/low slope during the day by looking for too-short daytime periods and comparing to the day/night mask value on preceding and following days. Can be combined with a clipping mask to ensure clipping is flagged as daytime.

Identify when the sun is up based on power or irradiance

---

pvanalytics/features/orientation.py
pvanalytics/tests/features/test_orientation.py

Was incorrectly returning minutes, now returns hours. 
Also revised implementation to use the `pandas.tseries` API instead of our own custom logic.

orientation._freqstr_to_hours returns hours

---

.github/workflows/lint-and-test.yml
.travis.yml

Python 3.5 has reached its end of life we no longer need to test on it.

Remove python 3.5 from CI builds

---

docs/api.rst
pvanalytics/system.py
pvanalytics/tests/conftest.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/test_system.py
requirements.txt
setup.py

Implements method for identifying tilt and azimuth given AC power, clear sky irradiance, and solar position.

Identify surface orientation from AC power and clearsky irradiance

---

pvanalytics/features/clipping.py
pvanalytics/features/daytime.py
pvanalytics/features/orientation.py
pvanalytics/quality/gaps.py
pvanalytics/quality/irradiance.py
pvanalytics/util/__init__.py
pvanalytics/util/_functions.py

Reduces duplicate code and removes brittle DIY solution, replacing it with calls to `pandas.tseries.frequencies.to_offset()`.
In looking at #83 I found that the older version of pandas does not work for the freqstr to timedelta conversion that was implemented previously. Good opportunity to refactor and reduce code duplication.

Reduce duplicate code for converting freqstr to Timedelta

---

pvanalytics/quality/outliers.py
pvanalytics/tests/quality/test_outliers.py
requirements.txt
setup.py

Rather than `scipy.stats.maximum_absolute_deviation()` we will use `statsmodels.robust.scale.mad()` to calculate the Maximum Absolute Deviation. This change will let us lower the minimum scipy version to 1.2 `scipy.stats.maximum_absolute_deviation()` was introduces in 1.3 (see #83).

Use statsmodels for maximum absolute deviation

---

docs/api.rst
pvanalytics/quality/time.py
pvanalytics/tests/quality/test_time.py

Given the dates on which daylight savings transitions occur, determine whether a series has DST by testing for a large shift between sunrise time in the week before and after the shift date.

Look for daylight savings shifts across specific dates

---

.github/workflows/lint-and-test.yml
.travis.yml
docs/index.rst
pvanalytics/quality/time.py
requirements-min.txt
requirements.txt
setup.py

Lowers minimum required version of pandas and numpy. Adds a CI job to test against the minimum version for all dependencies and fixes one bug related to the lower pandas version.

Apply NEP-29 guidelines for dependencies

---

.github/workflows/lint-and-test.yml

I mis-read the documentation on this. pull_request_target builds against the base workflow _and_ code. That is not the behavior I want, since it means the build does not test new code.

Revert pull_request_target trigger to pull_request

---

pvanalytics/features/clipping.py
pvanalytics/tests/features/test_clipping.py

Ignore missing data in clipping.levels()

---

docs/whatsnew/0.1.1.rst
pvanalytics/quality/outliers.py
pvanalytics/tests/quality/test_outliers.py

An update to `outliers.zscore` to expose the nan_policy.

updated outliers.zscore to include nan_policy

---

pvanalytics/tests/features/test_clearsky.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/test_system.py

This PR updates the test suite to not use the `orientation_strategy` ModelChain parameter (removed in v0.9.0).  Here is an example failed CI run from #114: https://github.com/pvlib/pvanalytics/runs/4398633530?check_suite_focus=true
At some point we will need to stop using `SingleAxisTracker` as well, but it still works for now.
- ~Closes #xxx~
- ~Added new API functions to `docs/api.rst`~
- ~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and …

Update test suite for pvlib v0.9.0

---

.github/workflows/lint-and-test.yml
docs/whatsnew/0.1.1.rst
requirements.txt
setup.py

This PR updates the requirements spec to prohibit `pandas==1.1.*`.  I figured there was little point in cooking up a workaround that works on all pandas versions because there were only ~6 months between 1.0.5 and 1.2.0 and it's been about a year since 1.2.0 was released.
I tested a range of pandas versions locally (windows) before opening this PR and include the results for reference:
- `pandas==1.1.0`: access violation/segfault
- `pandas>=1.1.1,<=1.1.5`: test failure
- `pandas>=1.2.0`: pass
- ~Added new API functions to `docs/api.rst`~
- ~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~
in …

Update pandas requirements

---

pvanalytics/util/_fit.py

Addresses issue #119, by updating the np.polyfit() function to newer np.polynomial.Polynomial.fit() function.

Updated the polyfit function to np.polynomial.Polynomial.fit()

---

docs/whatsnew/0.1.1.rst
pvanalytics/features/clearsky.py
pvanalytics/tests/features/test_clearsky.py

The sphinx build in #127 is failing because of #126, and I figured might as well fix #105 while we're at it.  
- ~[ ] Added new API functions to `docs/api.rst`~
- ~[ ] Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~
- ~[ ] Non-API functions clearly documented with docstrings or comments as necessary~
- ~[ ] Added tests to cover all new or modified code~

Get clearsky.reno tests passing again

---

docs/examples/clipping.py
docs/whatsnew/0.1.2.rst

This PR generates documentation for the clipping mask in pvlib.features. I added an example data set labeled for clipping, and compare the results of the mask to the ground-truth labeled data (taken from the Duramat data sets site). Related to issue https://github.com/pvlib/pvanalytics/issues/133.
or this Pull Request with `` :pull:`num` ``. Includes …

Clipping sphinx documentation

---

.github/workflows/lint-and-test.yml
docs/index.rst
pvanalytics/tests/quality/test_data_shifts.py
requirements.txt
setup.py

There are two main reasons we might want to have a requirements.txt:
- As an environment spec for users.  But pvanalytics is a library, not an application, so we prefer dependency ranges in `setup.py` over dependency versions in a requirements file.
- As an environment spec for testing, if you need specific versions beyond what's specified in setup.py.  We don't (currently) need that, so there's no need for a requirements.txt file either.  The exception is `requirements-min.txt`, which of course is not equivalent to setup.py.
This PR deletes `requirements.txt` so there's one less place to keep track of dependencies.  This required a bit of reworking of the CI configuration, which then uncovered some minor oversights in the tests.

Delete requirements.txt; related CI & test changes

---

docs/whatsnew/0.1.2.rst
docs/whatsnew/0.1.3.rst
docs/whatsnew/index.rst

- ~[ ] Added new API functions to `docs/api.rst`~
- ~[ ] Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~
and/or GitHub username (link with `` …

v0.1.2 Release

---

docs/whatsnew/0.1.3.rst
pvanalytics/quality/gaps.py

*Thank you for your contribution! Please provide a brief description of the problem and the proposed solution or new feature (if not already fully described in a linked issue)*
This PR speeds up the stale_data_round() function, by replacing the rolling + apply routine with a vectorized pandas routine.
or this Pull Request with `` :pull:`num` ``. Includes …

Stale data speedup

---

docs/whatsnew/0.1.4.rst
pvanalytics/__init__.py
pvanalytics/tests/test_pvanalytics.py
setup.py

Currently we aren't setting the `__version__` attribute in `__init__.py`, which means `pvanalytics.__version__` raises `AttributeError`.  This PR fixes that.

Fix `pvanalytics.__version__`

---

.github/workflows/pythonpublish.yml
docs/whatsnew/0.2.0.rst
docs/whatsnew/index.rst

Making a pre-release to support @kperrynrel's orientation estimation project.  Note that the `v0.2.0-alpha.1` name follows the recent pvlib convention; see https://github.com/pvlib/pvlib-python/tags
I've also changed the deploy-to-PyPI workflow to trigger on tags instead of GitHub Releases, with the thinking that we'll always make a tag when we want something to go to PyPI but we won't always want to make a GH Release (with pre-releases being an example).

What's new cleanup for v0.2.0-alpha.1

---

docs/whatsnew/0.2.0.rst
pvanalytics/metrics.py
pvanalytics/tests/conftest.py
pvanalytics/tests/features/test_clipping.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/features/test_shading.py
pvanalytics/tests/quality/test_data_shifts.py
pvanalytics/tests/quality/test_gaps.py
pvanalytics/tests/quality/test_irradiance.py
pvanalytics/tests/quality/test_outliers.py
pvanalytics/tests/quality/test_time.py
pvanalytics/tests/quality/test_util.py
pvanalytics/tests/quality/test_weather.py
pvanalytics/tests/test_system.py
requirements-min.txt
setup.py

~- [ ] Added tests to cover all new or modified code.~
~- [ ] Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings.~
~- [ ] Added new API functions to `docs/api.rst`.~
~- [ ] Non-API functions clearly documented with docstrings or comments as necessary.~
Various fixes in preparation for the upcoming release of pandas 2.0.0.  Mostly it comes down to using `pd.testing` …

Compatibility with pandas 2.0.0

---

docs/whatsnew/0.2.0.rst
pvanalytics/quality/time.py

The tests are failing in #186 due to unrelated changes in scipy (see the [1.11.0 release …

scipy 1.11 compatibility

---

.readthedocs.yml

ReadTheDocs is requiring a change in the configuration file (see the warning on this [build](https://readthedocs.org/projects/pvanalytics/builds/22179555/)):
> Your builds will stop working soon!
>"build.image" config key is deprecated and it will be removed soon. [Read our blog post to know how to migrate to new key "build.os"](https://blog.readthedocs.com/use-build-os-config/) and ensure your project continues building successfully.
This PR makes the necessary configuration updates.

Update RTD configuration

---

LICENSE

~~Closes #xxx~~
~~Added tests to cover all new or modified code.~~
~~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings.~~
~~Added new API functions to `docs/api.rst`.~~
~~Non-API functions clearly documented with docstrings or comments as necessary.~~
~~Adds description and name entries in the appropriate "what's new" file 
and/or GitHub username (link with `` :ghuser:`user` ``).~~
NREL copyright review of new code …

Update LICENSE per NREL legal review

---

docs/whatsnew/0.2.0.rst
pvanalytics/quality/time.py
pvanalytics/tests/quality/test_time.py

This update makes the changes to the original function so it now matches the finalized logic that I used for validation in the PVRW 2023 poster (https://www.nrel.gov/docs/fy23osti/85699.pdf). Most notably, we use binary segmentation instead of Pelt here, which results in a massive speedup while still being performant.

Update the time shift Ruptures function with the new logic that was tested/validated at PVRW 2023

---

docs/examples/clipping/clipping.py
docs/examples/day-night-masking/day-night-masking.py
docs/examples/gaps/data-completeness.py
docs/examples/gaps/stale-data.py
docs/examples/irradiance-quality/clearsky-limits-irradiance.py
docs/examples/metrics/variability-index.py
docs/examples/system/infer-orientation-fit-pvwatts.py
docs/examples/system/system-tracking.py
docs/examples/weather/module-temperature-check.py
docs/whatsnew/0.2.0.rst
pvanalytics/features/clearsky.py
pvanalytics/features/clipping.py
pvanalytics/quality/gaps.py
pvanalytics/quality/outliers.py
pvanalytics/system.py
pvanalytics/tests/conftest.py
pvanalytics/tests/features/test_clearsky.py
pvanalytics/tests/features/test_clipping.py
pvanalytics/tests/features/test_daytime.py
pvanalytics/tests/features/test_orientation.py
pvanalytics/tests/features/test_shading.py
pvanalytics/tests/quality/test_gaps.py
pvanalytics/tests/quality/test_irradiance.py
pvanalytics/tests/quality/test_time.py
pvanalytics/tests/quality/test_util.py
pvanalytics/tests/quality/test_weather.py
pvanalytics/tests/test_system.py

A recent [run](https://github.com/pvlib/pvanalytics/actions/runs/7606219430/job/20711650232?pr=202#step:5:832) of the test suite reported 262 warnings, mostly these deprecation warnings from pandas:
- `FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.`
- `FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.`
- `FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future …

Address various deprecations and test issues with pandas 2.2.0

---

.github/workflows/lint-and-test.yml
docs/whatsnew/0.2.0.rst
pvanalytics/tests/conftest.py
pvanalytics/tests/test_pvanalytics.py
setup.py

Keeping as draft for now, to see if the 3.12 jobs work smoothly.

Add Python 3.12 to test matrix

---

docs/whatsnew/0.2.0.rst
pvanalytics/quality/gaps.py
pvanalytics/tests/quality/test_gaps.py

Updated quality.gaps.trim function for updated versions of Pandas 2.0

Allow tz-aware timstamps in `gaps.trim`

---

docs/whatsnew/0.2.0.rst
pvanalytics/quality/irradiance.py
requirements-min.txt
setup.py

Recent CI runs show a deprecation warning from scipy: `scipy.integrate.trapz` is deprecated and …

Advance minimum scipy to 1.6

---

.github/workflows/lint-and-test.yml
docs/whatsnew/0.2.1.rst
requirements-min.txt
setup.py

Recent Mac OS CI jobs are failing.  I think updating the version of `setup-python` we're using will fix those, with the exception of python 3.7, which is no longer supported, so this PR drops py 3.7 here as well.

Drop python 3.7; fix Mac OS CI jobs

---

docs/whatsnew/0.2.1.rst
pvanalytics/quality/irradiance.py
pvanalytics/tests/quality/test_outliers.py

This PR adds compatibility for numpy 2.0, requiring minor changes (just `NaN` and `Inf` capitalization) to both the code base and the test suite.

Numpy 2.0 compatibility

---

docs/whatsnew/v0.2.3.rst
pvanalytics/features/clearsky.py

`reno` was accidentally passing `window_length` to the `infer_limits` parameter.  That means the window length was not being provided to the underlying pvlib function and instead the default was used.  It also means that, since non-zero numbers are truthy, presumably this function has effectively had `infer_limits=True`.
@cwhanse should `infer_limits=True` be retained here?

Fix issue with `window_length` in `reno` clearsky detection
