README.md
Describes the strucures and some of the specific goals served by that
structure. Gives a starting point for discussions/planning in the
issues.
=> Drafted initial library overview in README

.github/workflows/lint-and-test.yml, pvanalytics/tests/test_pvanalytics.py
Based on the pythonpackage template
=> Create lint and test workflow in github actions

setup.py
Adds a `setup.py` for packaging and publishing the library.
=> Configure setuptools

pvanalytics/quality/irradiance.py, pvanalytics/tests/quality/test_irradiance.py
=> Remove unused parameter from check_irradiance_consistency_qcrad

pvanalytics/features/clipping.py, pvanalytics/tests/features/test_clipping.py
There is currently only one feature (clipping), but this will set pvanalytics up for multiple methods of identifying each feature of interest and keep a clean/organized interface (`pvanalytics.features.<feature-name>.<method>`).
=> Refactor the features module making a submodule for each feature

.github/workflows/lint-and-test.yml
=> Add pull_request to triggers for ci workflow

pvanalytics/quality/gaps.py, pvanalytics/tests/quality/test_gaps.py
In `quality.gaps.stale_values_diff` and `quality.gaps.interpolation_diff`
Closes #41
=> increase default window to 6

pvanalytics/tests/conftest.py
=> Fix typo in name of `tz` parameter to `pvlib.location.Location`

README.md, docs/api.rst, docs/index.rst
=> Add library overview to documentation

pvanalytics/tests/quality/test_time.py
=> Add @requires_ruptures to test_shifts_ruptures_tz_localized()

docs/api.rst, pvanalytics/features/clipping.py, pvanalytics/tests/conftest.py, pvanalytics/tests/features/test_clipping.py
New clipping filter designed by Matt Muller and Kirsten Perry for PVFleets. Detects low slope periods and generated a clipping threshold for each day with such periods.
=> Geometric clipping

docs/index.rst
Add the `features.daytime` module to the library overview in `index.rst`.
=> Add features.daytime to library overview

.github/pull_request_template.md, docs/conf.py, docs/index.rst, docs/whatsnew/0.1.0.rst, docs/whatsnew/index.rst
Add release notes to documentation.
=> Release notes

.github/workflows/lint-and-test.yml, docs/api.rst, docs/whatsnew/0.1.1.rst, pvanalytics/metrics.py, pvanalytics/tests/features/test_clearsky.py, pvanalytics/tests/test_metrics.py
I'm tired of hunting down this function from some old script every time I want it... I'd rather just import it from pvanalytics instead :)
=> Create function to calculate variability index

docs/conf.py, pvanalytics/features/clipping.py, pvanalytics/features/shading.py, pvanalytics/quality/gaps.py, pvanalytics/quality/irradiance.py, pvanalytics/quality/outliers.py, pvanalytics/quality/time.py, pvanalytics/quality/weather.py, pvanalytics/system.py, setup.py
This PR:
- addresses a handful of small issues in the sphinx docs (missing parameter descriptions, incorrect parameter names, etc)
- enables intersphinx for a few packages
- updates the sphinx version used to build the docs
- ~Closes #xxx~
- ~Added new API functions to `docs/api.rst`~
- ~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~
in …
=> Small improvements to sphinx docs

pvanalytics/util/_fit.py
=> Remove trailling spaces

README.md, docs/index.rst, docs/whatsnew/0.1.2.rst, pvanalytics/__init__.py, pvanalytics/filtering.py, pvanalytics/fitting/__init__.py, pvanalytics/fitting/temperature.py
This PR updates our README and sphinx index files.  I'm not a big fan of the redundant descriptions between them, but OK for now I guess.  As it currently stands, this PR also removes a few "placeholder" modules; better to add those when there is some content to put in them IMHO.  If that's controversial I can revert.  
=> Miscellaneous doc and module cleanup

.github/pull_request_template.md, docs/whatsnew/0.1.3.rst
- ~~[ ] Added new API functions to `docs/api.rst`~~
- ~~[ ] Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~~
- ~~[ ] Non-API functions clearly documented with docstrings or comments as necessary~~
- ~~[ ] Added tests to cover all new or modified code~~
=> improve pull request template

LICENSE, docs/conf.py, docs/index.rst, docs/whatsnew/0.1.3.rst, docs/whatsnew/0.1.4.rst, docs/whatsnew/index.rst
Keeping as draft for now in the hopes of wrapping up #167 first.
=> v0.1.3 release

docs/whatsnew/0.1.4.rst, docs/whatsnew/index.rst, pvanalytics/quality/irradiance.py, pvanalytics/tests/features/test_clearsky.py, pvanalytics/tests/features/test_orientation.py, pvanalytics/tests/test_pvanalytics.py, pvanalytics/tests/test_system.py, requirements-min.txt, setup.py
=> Advance minimum pvlib to 0.9.4, and attendant cleanup

docs/examples/system/infer-orientation-fit-pvwatts.py, docs/whatsnew/0.1.4.rst, pvanalytics/system.py
Update the PVWatts calculations to better align with PVWatts 5 methodology. 
=> Updated to PVWatts5 methodology in the pvwatts orientation estimation function system.infer_orientation_fit_pvwatts()

.github/pull_request_template.md, README.md, docs/conf.py, docs/examples/weather/weather-limits.py, docs/index.rst, docs/whatsnew/0.1.4.rst, pvanalytics/quality/irradiance.py, setup.py
=> Switch docs to pydata-sphinx-theme

.github/workflows/lint-and-test.yml, docs/whatsnew/0.2.0.rst
=> Add Python 3.11 to test matrix

setup.py
- ~~[ ] Adds description and name entries in the appropriate "what's new" file 
and/or GitHub username (link with `` :ghuser:`user` ``).~~
The current maintainer information in the setup.py file is outdated. The PR proposes a convention similar to what is being done for pvlib-python.
=> Update maintainer in setup.py

docs/whatsnew/0.2.1.rst, docs/whatsnew/0.2.2.rst, docs/whatsnew/index.rst
=> Finalize v0.2.1

.github/workflows/lint-and-test.yml, docs/whatsnew/v0.2.3.rst
=> Add python 3.13 to test matrix

.github/workflows/lint-and-test.yml, .readthedocs.yml, docs/whatsnew/v0.2.3.rst, requirements-min.txt, setup.py
It reached EOL some time ago and is now failing to install in the CI.  Drop it!
=> Drop python 3.8
